networks:
  mail:
  ssl_mail:
    external: true

volumes:
  mail_data:
  mail_state:
  mail_logs:
  mail_config:
  webmail_db:
  webmail_web:

services:
  web_mail:
    image: nginx:alpine-slim
    container_name: web_mail
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HTTPS_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HTTPS_HOST}
      # LETSENCRYPT_HOST: mail.oppaiweeb.tech
      VIRTUAL_PORT: 80
    networks:
      - ssl_mail

  mail_server:
    image: mailserver/docker-mailserver:15.0
    container_name: mail_server
    restart: unless-stopped
    volumes:
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - mail_logs:/var/log/mail/
      - mail_config:/tmp/docker-mailserver/
      - ./postfix.cf:/tmp/docker-mailserver/postfix-main.cf
      - /etc/localtime:/etc/localtime:ro
      - ../01-SSL/certs/:/etc/letsencrypt/live/:ro
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HTTPS_HOST}
      PERMIT_DOCKER: none
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    hostname: ${SMTP_HOST_EIP}
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    stop_grace_period: 1m

