networks:
  ssl:
  ssl_jenkins:
    external: true
  ssl_git:
    external: true
  ssl_vpn:
    external: true
  ssl_orga:
    external: true
  ssl_reverseme:
    external: true
  ssl_mail:
    external: true
  ssl_pass:
    external: true
  ssl_ada:
    external: true
  ssl_eip:
    external: true
  ssl_post:
    external: true

volumes:
  nginx_conf:
  vhost:
  nginx_html:
  acme:

services:
  nginx_proxy:
    image: nginxproxy/nginx-proxy:1.6-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - ../06-Gitea/custom_nginx.conf:/etc/nginx/vhost.d/git.oppaiweeb.tech:ro
      - ../06-Gitea/custom_nginx.conf:/etc/nginx/vhost.d/git.wicgames.tech:ro
      - vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /run/docker.sock:/tmp/docker.sock:ro
    networks:
      - ssl
      - ssl_jenkins
      - ssl_git
      - ssl_vpn
      - ssl_orga
      - ssl_reverseme
      - ssl_mail
      - ssl_pass
      - ssl_eip
      - ssl_ada
      - ssl_post
    ports:
      - "80:80"
      - "443:443"

  acme_companion:
    image: nginxproxy/acme-companion:2.4
    container_name: nginx_proxy_acme
    restart: unless-stopped
    volumes_from:
      - nginx_proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=admin@mail.oppaiweeb.tech
    networks:
      - ssl

